### ISSUE TITLE
Item的点击事件方法和AspectJ一起用时，混淆后点击报错

### ISSUE THREAD

**Issue by ling9400** [hongyangAndroid/baseAdapter#130]
如题，用AspectJ方法注解Item的点击事件，混淆后点击Item报错，错误信息如下：
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.annotation.Annotation java.lang.reflect.Method.getAnnotation(java.lang.Class)' on a null object reference
        
        at com.zhy.adapter.recyclerview.MultiItemTypeAdapter$1.onClick(MultiItemTypeAdapter.java:68)
        at android.view.View.performClick(View.java:6648)
        at android.view.View.performClickInternal(View.java:6620)
        at android.view.View.access$3100(View.java:787)
        at android.view.View$PerformClick.run(View.java:26167)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)

**Comment by debbiefu** [comment]
解决了吗，也遇到这个问题了
