### ISSUE TITLE
加载更多的时候点击最后一个item会出现越界

### ISSUE THREAD

**Issue by Javen205** [hongyangAndroid/baseAdapter#33]
如题 

等加载完成之后点击就又没有问题了 

`07-13 11:12:22.116 6026-6026/com.movieapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                            java.lang.IndexOutOfBoundsException: Invalid index 118, size is 118
                                                                at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                at java.util.ArrayList.get(ArrayList.java:308)
                                                                at com.zhy.adapter.recyclerview.MultiItemTypeAdapter$1.onClick(MultiItemTypeAdapter.java:72)
                                                                at android.view.View.performClick(View.java:4240)
                                                                at android.view.View$PerformClick.run(View.java:17752)
                                                                at android.os.Handler.handleCallback(Handler.java:730)
                                                                at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                at android.os.Looper.loop(Looper.java:137)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5473)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:525)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
                                                                at dalvik.system.NativeStart.main(Native Method)`

**Comment by sunflowerseat** [comment]
没法贴文件，改一下Adapter里面改一下position为position-1就行了， 其实直接使用洋神的Adapter有点问题的， 获取的数据都不对的， 洋神那个CommonAdapter继承了MutiAdapter，其实重新改写一下CommonAdapter就行了。需要的话加群，修改后的代码贴在群共享里 283272067

**Comment by haonan1** [comment]
@Javen205 你的问题解决了没
