### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1

### ISSUE THREAD

**Issue by General110** [hongyangAndroid/baseAdapter#61]
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
at java.util.ArrayList.get(ArrayList.java:310)
at com.zhy.adapter.recyclerview.MultiItemTypeAdapter$1.onClick(MultiItemTypeAdapter.java:72)
at android.view.View.performClick(View.java:4785)
at android.view.View$PerformClick.run(View.java:19919)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5399)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)

**Comment by xiaobailong24** [comment]
@General110 遇到同样的问题，请问您是怎么解决的？
